[[manager.prepend_keymap]]
on = "V"
run = ["toggle", "arrow 1"]
desc = "Toggle the current selection state"

[[manager.prepend_keymap]]
on = ["<Space>", "f"]
run = "plugin fzf"
desc = "Jump to a file/directory via fzf"

[[manager.prepend_keymap]]
on = "Z"
run = "filter --smart"
desc = "Filter files"

[[manager.prepend_keymap]]
on = ["<C-e>"]
run = "seek 5"

[[manager.prepend_keymap]]
on = ["<C-y>"]
run = "seek -5"

# eza-preview
[[manager.prepend_keymap]]
on = ["E"]
run = "plugin eza-preview"
desc = "Toggle tree/list dir preview"

[[manager.prepend_keymap]]
on = ["-"]
run = "plugin eza-preview --args='--inc-level'"
desc = "Increment tree level"

[[manager.prepend_keymap]]
on = ["_"]
run = "plugin eza-preview --args='--dec-level'"
desc = "Decrement tree level"

[[manager.prepend_keymap]]
on = ["$"]
run = "plugin eza-preview --args='--toggle-follow-symlinks'"
desc = "Toggle tree follow symlinks"

# yamb
[[manager.prepend_keymap]]
on = ["<Space>", "a"]
run = "plugin yamb --args=save"
desc = "Add bookmark"

[[manager.prepend_keymap]]
on = ["<Space>", "g"]
run = "plugin yamb --args=jump_by_key"
desc = "Jump bookmark by key"

[[manager.prepend_keymap]]
on = ["<Space>", "<Space>"]
run = "plugin yamb --args=jump_by_fzf"
desc = "Jump bookmark by fzf"

[[manager.prepend_keymap]]
on = ["<Space>", "d"]
run = "plugin yamb --args=delete_by_key"
desc = "Delete bookmark by key"

[[manager.prepend_keymap]]
on = ["<Space>", "D"]
run = "plugin yamb --args=delete_by_fzf"
desc = "Delete bookmark by fzf"

[[manager.prepend_keymap]]
on = ["<Space>", "A"]
run = "plugin yamb --args=delete_all"
desc = "Delete all bookmarks"

# jump-to-char
[[manager.prepend_keymap]]
on = "f"
run = "plugin jump-to-char"
desc = "Jump to char"

# compress.yazi
[[manager.prepend_keymap]]
on = ["c", "a"]
run = "plugin compress"
desc = "Archive selected files"

# diff.yazi
[[manager.prepend_keymap]]
on = "<C-d>"
run = "plugin diff"
desc = "Diff the selected with the hovered file"

[[manager.prepend_keymap]]
on = "T"
run = "plugin max-preview"
desc = "Maximize or restore preview"
